# Generated by Django 4.2.2 on 2024-04-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(verbose_name='category_id')),
                ('category', models.CharField(max_length=128, verbose_name='category_title')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='photo')),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='avg_rating')),
            ],
            options={
                'db_table': 'view_catalog',
                'ordering': ['category', 'catalog_title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=128, unique=True, verbose_name='category_title')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daten', models.DateTimeField(verbose_name='daten')),
                ('news_title', models.CharField(max_length=256, verbose_name='news_title')),
                ('details', models.TextField(verbose_name='news_details')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='news_photo')),
            ],
            options={
                'db_table': 'news',
                'ordering': ['daten'],
                'indexes': [models.Index(fields=['daten'], name='news_daten_a29edb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_title', models.CharField(max_length=255, verbose_name='catalog_title')),
                ('details', models.TextField(blank=True, null=True, verbose_name='catalog_details')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='catalog_price')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='catalog_photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_category', to='product.category')),
            ],
            options={
                'db_table': 'catalog',
                'ordering': ['catalog_title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_review', models.DateTimeField(auto_now_add=True, verbose_name='date_review')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('details', models.TextField(verbose_name='review_details')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_catalog', to='product.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
                'ordering': ['date_review'],
                'indexes': [models.Index(fields=['date_review'], name='review_date_re_e06954_idx')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_question', models.DateTimeField(auto_now_add=True, verbose_name='date_question')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='answer')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_catalog', to='product.catalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question',
                'ordering': ['date_question'],
                'indexes': [models.Index(fields=['date_question'], name='question_date_qu_f1052b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='catalog',
            index=models.Index(fields=['catalog_title'], name='catalog_catalog_d497ec_idx'),
        ),
    ]
