# Generated by Django 4.2.2 on 2024-04-05 11:30
from pickle import FALSE, TRUE
from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from django.db import migrations
# Подключаем модуль для работы с датой/веременем
from datetime import datetime, timedelta
# Подключаем модкль генерации случайных чисел
import random

# Найти или Добавить Категорию
global dict_category
dict_category = {}

def get_category(apps, val):   
    # Поиск категории
    if val in dict_category.values():
        for k, v in dict_category.items():
            if v == val:
                return k    
    else:
        Category = apps.get_model("product", "Category")
        category = Category()
        category.category_title = val
        category.save()
        dict_category[category.id] = category.category_title
        return category.id

# Добавить товар 
def insert_catalog(apps, param_catalog):   
    Catalog = apps.get_model("product", "Catalog")
    catalog = Catalog()
    catalog.category_id = param_catalog[0]
    catalog.catalog_title = param_catalog[1]
    catalog.details = param_catalog[2]
    catalog.price = param_catalog[3]
    catalog.photo = param_catalog[4]
    catalog.save()
    return

# Добавить отзыв на товар 
def insert_review(apps, param_review):   
    Review = apps.get_model("product", "Review")
    review = Review()
    review.date_review = param_review[0]
    review.catalog_id = param_review[1]
    review.user_id = param_review[2]
    review.rating = param_review[3]
    review.details = param_review[4]
    review.save()
    review.date_review = param_review[0]
    review.save()
    return

# Добавить Вопросы и ответы 
def insert_question(apps, param_question):   
    Question = apps.get_model("product", "Question")
    question = Question()
    question.date_question = param_question[0]
    question.catalog_id = param_question[1]
    question.user_id = param_question[2]
    question.question = param_question[3]
    question.answer = param_question[4]
    question.save()
    question.date_question = param_question[0]
    question.save()
    return

# Добавить Новости
def insert_news(apps, param):
    News = apps.get_model("product", "News")
    news = News()
    news.daten = param[0]
    news.news_title = param[1]
    news.details = param[2]
    news.photo = param[3]
    news.save()
    return 

# Начальные данные 
def new_data(apps, schema_editor):
    try:
        # Суперпользователь id=1
        user = User.objects.create_superuser(username='root',
        email='shop120424@mail.ru',
        first_name='Руслан', 
        last_name='Кусаинов',
        password='SsNn5678+-@')
        print("Суперпользователь создан")
    
        # Группа менеджеров
        managers = Group.objects.get_or_create(name = 'Managers')
        managers = Group.objects.get(name='Managers')
        print("Группа менеджеров создана")
    
        # Пользователь с ролью менеджера id=2
        user = User.objects.create_user(username='manager', password='Ss0066+-', email='manager@mail.ru', first_name='Вадим', last_name='Куляев')
        managers.user_set.add(user)
        print("Менеджер добавлен в группу менеджеров")

        # Простые пользователи () id3-22
        user = User.objects.create_user(username='user1', password='Uu0066+-', email='user1@mail.ru', first_name='Динара', last_name='Махан')
        user = User.objects.create_user(username='user2', password='Uu0066+-', email='user2@mail.ru', first_name='Алтыншаш ', last_name='Бабашева')
        user = User.objects.create_user(username='user3', password='Uu0066+-', email='user3@mail.ru', first_name='Айман', last_name='Жалғасбаева')
        user = User.objects.create_user(username='user4', password='Uu0066+-', email='user4@mail.ru', first_name='Амир', last_name='Дандамаев')
        user = User.objects.create_user(username='user5', password='Uu0066+-', email='user5@mail.ru', first_name='Самат', last_name='Жұмабек')
        user = User.objects.create_user(username='user6', password='Uu0066+-', email='user6@mail.ru', first_name='Камалбек', last_name='Көшербаев')
        user = User.objects.create_user(username='user7', password='Uu0066+-', email='user7@mail.ru', first_name='Альбина', last_name='Алангузова')
        user = User.objects.create_user(username='user8', password='Uu0066+-', email='user8@mail.ru', first_name='Жанел', last_name='Кабдуллина')
        user = User.objects.create_user(username='user9', password='Uu0066+-', email='user9@mail.ru', first_name='Арман', last_name='Қайратов')
        user = User.objects.create_user(username='user10', password='Uu0066+-', email='user10@mail.ru', first_name='Айдана ', last_name='Ермекова')        
        user = User.objects.create_user(username='user11', password='Uu0066+-', email='user11@mail.ru', first_name='Күлайым', last_name='Бекмырза')
        user = User.objects.create_user(username='user12', password='Uu0066+-', email='user12@mail.ru', first_name='Альбина', last_name='Ашимтаева')
        user = User.objects.create_user(username='user13', password='Uu0066+-', email='user13@mail.ru', first_name='Диас', last_name='Аубакиров')
        user = User.objects.create_user(username='user14', password='Uu0066+-', email='user14@mail.ru', first_name='Юрий', last_name='Морхов')
        user = User.objects.create_user(username='user15', password='Uu0066+-', email='user15@mail.ru', first_name='Виктор', last_name='Гарнов')
        user = User.objects.create_user(username='user16', password='Uu0066+-', email='user16@mail.ru', first_name='Дамира', last_name='Токубаева')
        user = User.objects.create_user(username='user17', password='Uu0066+-', email='user17@mail.ru', first_name='Ержан', last_name='Дүйсенғалиев')
        user = User.objects.create_user(username='user18', password='Uu0066+-', email='user18@mail.ru', first_name='Ксения', last_name='Воробьева')
        user = User.objects.create_user(username='user19', password='Uu0066+-', email='user19@mail.ru', first_name='Жибек', last_name='Исаханова')
        user = User.objects.create_user(username='user20', password='Uu0066+-', email='user20@mail.ru', first_name='Сабит', last_name='Кабиден')        
        print("Созданы простые пользователи")

        #1 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40-46""", 2000, "images/catalog01.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=30) + timedelta(minutes=random.randint(1, 240)), 1, 3, 5, "Нормальные тапочки, за свою цену. Подошли мужчине с большим подъемом. Так что товар рекомендую "]		
        insert_review(apps, parameters) 

        #2 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40, 41, 44, 45, 46""", 2000, "images/catalog02.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=30) + timedelta(minutes=random.randint(1, 240)), 2, 3, "Подскажите, пожалуйста, подошва тапочек гнется, или скорее твердая?", "Здравствуйте! Гнется"]		
        insert_question(apps, parameters) 

        #3 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40-46""", 2500, "images/catalog03.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=29) + timedelta(minutes=random.randint(1, 240)), 3, 4, 5, "Подкрадули прям зачётные! Веселые! Ноги не потеют, не порвались за пару месяцев и не развалились. "]		
        insert_review(apps, parameters) 

        #4 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40-45""", 2000, "images/catalog04.jpg"]		
        insert_catalog(apps, parameters)   

        #5 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40-46""", 2200, "images/catalog05.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=28) + timedelta(minutes=random.randint(1, 240)), 5, 5, 3, "Через месяц начала рваться ткань вдоль подошвы"]		
        insert_review(apps, parameters) 

        #6 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40-46""", 2100, "images/catalog06.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=28) + timedelta(minutes=random.randint(1, 240)), 6, 4, "Какая гарантия на тапочки?", "Здравствуйте! Детские домашние тапочки Домашки имеют гарантию в течении месяца после покупки"]		
        insert_question(apps, parameters) 

        #7 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40-46""", 2300, "images/catalog07.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=27) + timedelta(minutes=random.randint(1, 240)), 7, 6, 5, "Легкие тапки, симпатичные, соответстауют этим размерам, поэтому оказались большие, обычно тапки покупали всегда на размер больше "]		
        insert_review(apps, parameters) 

        #8 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Мужские домашние тапочки", """📐Размеры: 40-46""", 2400, "images/catalog08.jpg"]		
        insert_catalog(apps, parameters)   

        #9 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 36-41""", 2000, "images/catalog09.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=26) + timedelta(minutes=random.randint(1, 240)), 9, 7, 5, "Хороший подарок, соответствует размеру"]		
        insert_review(apps, parameters) 

        #10 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 36-41""", 2400, "images/catalog10.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=26) + timedelta(minutes=random.randint(1, 240)), 10, 5, "Есть ли супинатор (подсводник) на стельке?", "Добрый день. Супинатора в детских домашних тапочках нет."]		
        insert_question(apps, parameters) 

        #11 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 36-41""", 2700, "images/catalog11.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=25) + timedelta(minutes=random.randint(1, 240)), 11, 8, 5, "Классные, рекомендую"]		
        insert_review(apps, parameters) 

        #12 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 36-41""", 2400, "images/catalog12.jpg"]		
        insert_catalog(apps, parameters)   

        #13 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 35, 36, 37, 38, 39, 41""", 2100, "images/catalog13.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=24) + timedelta(minutes=random.randint(1, 240)), 13, 9, 5, "Сперва непривычно, но потом все ок"]		
        insert_review(apps, parameters) 

        #14 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 36, 37, 39, 40, 41, 42""", 2300, "images/catalog14.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=24) + timedelta(minutes=random.randint(1, 240)), 14, 6, "Здравствуйте. Длина стопы 15 см, какой размер нужно выбрать?", "Добрый день. 35"]		
        insert_question(apps, parameters) 

        #15 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 37, 38, 39, 40, 41""", 2500, "images/catalog15.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=23) + timedelta(minutes=random.randint(1, 240)), 15, 10, 5, "Ощущения при ходьбе приятные, расслабляющие. "]		
        insert_review(apps, parameters) 

        #16 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: EC-3F(8H)
📐Размеры: 35, 36, 37, 38, 39""", 2400, "images/catalog16.jpg"]		
        insert_catalog(apps, parameters)   

        #17 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """📐Размеры: 36-41""", 2400, "images/catalog17.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=22) + timedelta(minutes=random.randint(1, 240)), 17, 11, 5, "Хорошие тапочки, массируют усталые ножки "]		
        insert_review(apps, parameters) 

        #18 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Сабо", """📐Размеры: 42, 43, 44, 45, 46""", 3500, "images/catalog18.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=22) + timedelta(minutes=random.randint(1, 240)), 18, 7, "Здравствуйте. Подскажите, пожалуйста, на какую полноту ноги подойдёт обувь?", "Добрый день. Стандартную"]		
        insert_question(apps, parameters) 

        #19 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Сабо", """📐Размеры: 35, 38, 39, 40, 41""", 4000, "images/catalog19.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=21) + timedelta(minutes=random.randint(1, 240)), 19, 12, 4, "Низкая, западающая пятка"]		
        insert_review(apps, parameters) 

        #20 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: NP-2F
📐Размеры: 36-41""", 2500, "images/catalog20.jpg"]		
        insert_catalog(apps, parameters)   

        #21 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: ES-5B
📐Размеры: 35, 36, 37, 38, 39, 40""", 2400, "images/catalog21.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=20) + timedelta(minutes=random.randint(1, 240)), 21, 13, 5, "Обалденнные тапочки!"]		
        insert_review(apps, parameters) 

        #22 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: ES-5B
📐Размеры: 38, 39, 40, 41""", 2100, "images/catalog22.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=20) + timedelta(minutes=random.randint(1, 240)), 22, 8, "А верх тапочек действительно х/б? Нога не будет потеть. Такое ощущение, что это синтетика", "Здравствуйте! Материал верха состоит их 3-х материалов общей плотностью более 400гр/м2."]		
        insert_question(apps, parameters) 

        #23 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: CA-5F
📐Размеры: 37, 38, 39, 41""", 2200, "images/catalog23.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=19) + timedelta(minutes=random.randint(1, 240)), 23, 14, 5, "Через"]		
        insert_review(apps, parameters) 

        #24 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: NP-3E
📐Размеры: 36, 37, 38, 39, 41""", 2300, "images/catalog24.jpg"]		
        insert_catalog(apps, parameters)   

        #25 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: NP-3E
📐Размеры: 37, 38, 39, 41""", 2400, "images/catalog25.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=18) + timedelta(minutes=random.randint(1, 240)), 25, 15, 5, "Тапочки супер, взяла себе и дочке"]		
        insert_review(apps, parameters) 

        #26 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: NC-4X
📐Размеры: 36, 37, 39, 41""", 3000, "images/catalog26.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=18) + timedelta(minutes=random.randint(1, 240)), 26, 9, "Здравствуйте, скользят ли тапочки?", "Добрый день. Материал подошвы - облегчённая пористая резина ЭВА. На большинстве поверхностей в том числе кафеле подошва не скользит."]		
        insert_question(apps, parameters) 

        #27 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Тапочки"), "Женские домашние тапочки", """🏷️Артикул: NC-7F
📐Размеры: 36, 37, 39, 40""", 2600, "images/catalog27.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=17) + timedelta(minutes=random.randint(1, 240)), 27, 16, 5, "Тапочки супер, уже брала такие"]		
        insert_review(apps, parameters) 

        #28 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Сорочка"), "Ночная сорочка", """🏷️Артикул: 1907
📐Размеры: 48-56""", 12000, "images/catalog28.jpg"]		
        insert_catalog(apps, parameters)   

        #29 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Сорочка"), "Ночная сорочка", """🏷️Артикул: 1955
📐Размеры: 52-58""", 10000, "images/catalog29.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=16) + timedelta(minutes=random.randint(1, 240)), 29, 17, 5, "Немного свободна, если при стирке сядет будет совсем отлично, но и так не плохо "]		
        insert_review(apps, parameters) 

        #30 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Сорочка"), "Ночная сорочка", """🏷️Артикул: 1233
📐Размеры: 44-52""", 11000, "images/catalog30.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=16) + timedelta(minutes=random.randint(1, 240)), 30, 10, "Здравствуйте, Какая ткань", "Здравствуйте. Материал Шуйский ситец, 100% хлопок"]		
        insert_question(apps, parameters) 

        #31 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Сорочка"), "Ночная сорочка", """🏷️Артикул: 1237
📐Размеры: 52-62""", 12000, "images/catalog31.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=15) + timedelta(minutes=random.randint(1, 240)), 31, 18, 5, "Ткань очень приятная, сорочка очень красивая, все аккуратно прошито "]		
        insert_review(apps, parameters) 

        #32 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Сорочка"), "Ночная сорочка", """🏷️Артикул: 1988
📐Размеры: 48-58""", 11000, "images/catalog32.jpg"]		
        insert_catalog(apps, parameters)   

        #33 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Халат"), "Халат женский велюровый", """🏷️Артикул: 3764
📐Размеры: 48-58""", 10000, "images/catalog33.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 240)), 33, 19, 5, "Удобный и стильный халатик."]		
        insert_review(apps, parameters) 

        #34 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 7719
📐Размеры: 44-56""", 11000, "images/catalog34.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=14) + timedelta(minutes=random.randint(1, 240)), 34, 11, "Добрый день, материал не садится после стирки?", "Добрый день, нет"]		
        insert_question(apps, parameters) 

        #35 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 7531
📐Размеры: 42-44, 46-48, 50-52, 54-56""", 12000, "images/catalog35.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=13) + timedelta(minutes=random.randint(1, 240)), 35, 20, 5, "Хороший костюм. Пока не стирала и не одевала. Дополню позж"]		
        insert_review(apps, parameters) 

        #36 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 7519
📐Размеры: 44-56""", 10000, "images/catalog36.jpg"]		
        insert_catalog(apps, parameters)   

        #37 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 7517
📐Размеры: 44-52""", 11000, "images/catalog37.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(1, 240)), 37, 21, 5, "Приятная ткань, принт как на фото. Рекомендую"]		
        insert_review(apps, parameters) 

        #38 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 7517
📐Размеры: 44-52""", 12000, "images/catalog38.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=12) + timedelta(minutes=random.randint(1, 240)), 38, 12, "Подскажите, на какой рост комплект с брюками?", "Добрый день, 160-170 см"]		
        insert_question(apps, parameters) 

        #39 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Платье"), "Платье женское", """🏷️Артикул: 4992
📐Размеры: 50-58""", 14000, "images/catalog39.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), 39, 22, 5, "Платье супер, очень довольна"]		
        insert_review(apps, parameters) 

        #40 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 1070090294
📐Размеры: M, L, XL, 2XL""", 11500, "images/catalog40.jpg"]		
        insert_catalog(apps, parameters)   

        #41 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 1052160000
📐Размеры: S, M, L, XL""", 13500, "images/catalog41.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), 41, 3, 4, "На штанах полезли нитки, распоролся край, пуговица на кофте отпала. "]		
        insert_review(apps, parameters) 

        #42 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 1115130308
📐Размеры: XL, 2XL, 3XL, 4XL""", 13700, "images/catalog42.jpg"]		
        insert_catalog(apps, parameters)   

        #43 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 7964
📐Размеры: 48-56""", 14500, "images/catalog43.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), 43, 4, 5, "Великолепный домашний комплект ! Ткань приятная у телу , строчки ровные , идёт в размер"]		
        insert_review(apps, parameters) 

        #44 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 60143
📐Размеры: S, M, L, XL""", 11600, "images/catalog44.jpg"]		
        insert_catalog(apps, parameters)   

        #45 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Костюм женский для дома и отдыха", """🏷️Артикул: 28024
📐Размеры: L, 2XL, 3XL""", 10400, "images/catalog45.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), 45, 5, 5, "Хороший домашний костюм"]		
        insert_review(apps, parameters) 

        #46 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Мужской костюм для дома и отдыха", """🏷️Артикул: 93442
📐Размеры: M, L, XL, 2XL""", 9000, "images/catalog46.jpg"]		
        insert_catalog(apps, parameters)   

        #47 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Костюм"), "Мужской костюм для дома и отдыха", """🏷️Артикул: 93353
📐Размеры: M, L, XL, 2XL""", 10300, "images/catalog47.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), 47, 6, 5, "Цвет очень красивый, а сам он очень мягкий и приятный к телу"]		
        insert_review(apps, parameters) 

        #48 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Носки женские"), "Носки женские", """Носки женские""", 1000, "images/catalog48.jpg"]		
        insert_catalog(apps, parameters)   

        #49 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Носки женские"), "Носки женские", """Носки женские""", 950, "images/catalog49.jpg"]		
        insert_catalog(apps, parameters)   
        parameters = [datetime.now() - timedelta(days=11) + timedelta(minutes=random.randint(1, 240)), 49, 7, 5, "Хорошее качество"]		
        insert_review(apps, parameters) 

        #50 Каталог parameters - товар, (категория, название, описание, цена, фото)
        parameters = [get_category(apps, "Носки женские"), "Носки женские", """Носки женские""", 980, "images/catalog50.jpg"]		
        insert_catalog(apps, parameters)   
        print("Созданы Каталог")

        #Новости
        #parameters = [datetime.now() - timedelta(days=10) + timedelta(minutes=random.randint(1, 240)), "Заголовок", """Детали""", "images/news1.jpg" ]
        #insert_news(apps, parameters)
        parameters = ['2024-02-25 12:00:00', "С 1 марта магазин Oliver работает в воскресенье", """С 1 марта магазин Oliver работает в воскресенье""", "images/news1.jpg" ]
        insert_news(apps, parameters)
        parameters = ['2024-03-01 13:00:00', "С 6 по 8 марта скидка 10% на все!", """С 6 по 8 марта скидка 10% на все!""", "images/news2.jpg" ]
        insert_news(apps, parameters)
        parameters = ['2024-03-08 14:00:00', "С праздником 8 марта!", """Поздравляем с праздником 8 марта!""", "images/news3.jpg" ]
        insert_news(apps, parameters)
        parameters = ['2024-03-15 15:00:00', "Новое поступление", """Новое поступление""", "images/news4.jpg" ]
        insert_news(apps, parameters)
        parameters = ['2024-03-20 16:00:00', "Акция к Наурыз", """Акция к Наурыз. С 21 по 25 марта на постельное белье 1+1=3""", "images/news5.jpg" ]
        insert_news(apps, parameters)
        parameters = ['2024-03-28 12:00:00', "Акция", """Скидка на постельное белье 20%""", "images/news6.jpg" ]
        insert_news(apps, parameters)
        parameters = ['2024-04-05 13:00:00', "Подарочные сертификаты", """У нас Вы можете приобрести подарочные сертификаты номиналом 5000, 10000, 15000 тнг""", "images/news7.jpg" ]
        insert_news(apps, parameters)
        print("Созданы Новости")

    except Exception as error:
        print(error)

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(new_data),
        migrations.RunSQL("""CREATE VIEW view_catalog AS
SELECT catalog.id, catalog.category_id, category.category_title AS category, catalog.catalog_title, catalog.details, catalog.price, catalog.photo, 
(SELECT AVG(rating) FROM review WHERE review.catalog_id = catalog.id) AS avg_rating
FROM catalog LEFT JOIN category ON catalog.category_id = category.id;"""),

    ]
